version: '3.4'

services:
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile

  project1:
    image: ${DOCKER_REGISTRY-}project1
    build:
      context: .
      dockerfile: Services/Project1/Dockerfile
    depends_on:
      - rabbitmq

  project2:
    image: ${DOCKER_REGISTRY-}project2
    build:
      context: .
      dockerfile: Services/Project2/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  #identitymssql:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  #  container_name: identitymssql
  #  ports:
  #    - "1433:1433"
  #  environment:
  #    - ACCEPT_EULA="Y"
  #    - SA_PASSWORD="password1"

   # networks:
    #    - rabbitmq_go_net

#networks:
 # rabbitmq_go_net:
  #  driver: bridge
  cqrsexample:
    image: ${DOCKER_REGISTRY-}cqrsexample
    build:
      context: .
      dockerfile: Services/CqrsExample/Dockerfile


  3layerexample:
    image: ${DOCKER_REGISTRY-}3layerexample
    build:
      context: .
      dockerfile: Services/3LayerExample/Dockerfile

