version: '3.4'

services:
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile

  project1:
    image: ${DOCKER_REGISTRY-}project1
    build:
      context: .
      dockerfile: Services/Project1/Dockerfile
    depends_on:
      - rabbitmq

  project2:
    image: ${DOCKER_REGISTRY-}project2
    build:
      context: .
      dockerfile: Services/Project2/Dockerfile
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
   # networks:
    #    - rabbitmq_go_net

#networks:
 # rabbitmq_go_net:
  #  driver: bridge

