version: '3.4'

services:
  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile

  project1:
    image: ${DOCKER_REGISTRY-}project1
    build:
      context: .
      dockerfile: Services/Project1/Dockerfile


  project2:
    image: ${DOCKER_REGISTRY-}project2
    build:
      context: .
      dockerfile: Services/Project2/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

